package com.avariohome.avario;


/**
 * Created by aeroheart-c6 on 25/12/2016.
 */
public interface Constants {
    int MQTT_QOS = 1; // at least once

    int TOUCH_TIMEMIN_DOUBLETAP = 40;
    int TOUCH_TIMEOUT_DOUBLETAP = 200;
    int TOUCH_TIMEOUT_LONGTAP = 500;
    int TOUCH_SLOP_SCROLL = 8;
    int TOUCH_SLOP_DOUBLETAP = 100;

    float MAX_VALUE_NUMBER = 255.0f;
    float MAX_VALUE_COVER = 100.0f;
    float MAX_VALUE_VOLUME = 100.0f;

    String ENTITY_COVER_STATE_OPENING = "opening";
    String ENTITY_COVER_STATE_CLOSING = "closing";
    String ENTITY_COVER_STATE_OPENED = "open";
    String ENTITY_COVER_STATE_CLOSED = "closed";
    String ENTITY_COVER_STATE_PARTIAL = "partial";
    String ENTITY_COVER_STATE_UNKNOWN = "unknown";

    String ENTITY_MEDIA_STATE_PLAYING = "playing";
    String ENTITY_MEDIA_STATE_PAUSED = "paused";
    String ENTITY_MEDIA_STATE_STOPPED = "idle";
    String ENTITY_MEDIA_STATE_CLOSED = "off";

    // Mqtt Event Types
    String MQTT_EVENT_TYPE_STATE_CHANGED = "state_changed";
    String MQTT_EVENT_TYPE_ROOM_CHANGED = "room_changed";
    String MQTT_EVENT_TYPE_BOOTSTRAP_CHANGED = "bootstrap_changed";

    // Error Codes
//    int ERROR_APP_UNEXPECTED = 0x00000;
//    int ERROR_APP_UNREGISTERED = 0x00010;
    int ERROR_APP_SETTINGS = 0x00020;
    int ERROR_APP_NOT_INSTALLED = 0x00030;

    int ERROR_BOOTSTRAP_UNREACHABLE = 0x00100;
    int ERROR_BOOTSTRAP_AUTHENTICATION = 0x00110;
    int ERROR_BOOTSTRAP_INVALID = 0x00120;

    int ERROR_ASSET_UNREACHABLE = 0x00200;

    int ERROR_MQTT_AUTHENTICATION = 0x00400;
    int ERROR_MQTT_CONNECTION = 0x00410;
    //    int ERROR_MQTT_DISCONNECTION = 0x00420;
    int ERROR_MQTT_SUBSCRIPTION = 0x00430;
    int ERROR_MQTT_CONFIGURATION = 0x00440;
    int ERROR_MQTT_PAYLOAD = 0x00450;
    int ERROR_MQTT_DISCONNECTED = 0x004FF;

    int ERROR_STATE_MISSINGKEY = 0x00300;
    int ERROR_STATE_FORBIDDEN = 0x00310;
    int ERROR_STATE_MQTT_INVALID = 0x00320;
    int ERROR_STATE_MQTT_TYPE = 0x00321;
    int ERROR_STATE_API_OBJECTS = 0x00330;
    int ERROR_STATE_API_CONDITION = 0x00340;
//    int ERROR_STATE_EVALUATION = 0x00350;

    int ERROR_API_TIMEOUT = 0x01000;
    int ERROR_API_NETWORK = 0x01010;
    int ERROR_API_PARSE = 0x01020;
    //    int ERROR_API_HTTP_CLIENT = 0x01400;
//    int ERROR_API_HTTP_AUTH = 0x01401;
//    int ERROR_API_HTTP_FORBIDDEN = 0x01403;
//    int ERROR_API_HTTP_NOT_FOUND = 0x01404;
//    int ERROR_API_HTTP_METHOD = 0X01405;
//    int ERROR_API_HTTP_UNACCEPTABLE = 0x01406;
    int ERROR_API_HTTP_SERVER = 0x01500;

    int ERROR_CURRENTSTATE_NETWORK = 0x02000;
    int ERROR_CURRENTSTATE_TIMEOUT = 0x02010;
    int ERROR_CURRENTSTATE_PARSE = 0x02020;
    //    int ERROR_CURRENTSTATE_HTTP_CLIENT = 0x02400;
//    int ERROR_CURRENTSTATE_HTTP_AUTH = 0x02401;
//    int ERROR_CURRENTSTATE_HTTP_FORBIDDEN = 0x02403;
//    int ERROR_CURRENTSTATE_HTTP_NOT_FOUND = 0x02404;
//    int ERROR_CURRENTSTATE_HTTP_METHOD = 0x02405;
//    int ERROR_CURRENTSTATE_HTTP_UNACCEPTABLE = 0x02406;
    int ERROR_CURRENTSTATE_HTTP_SERVER = 0x02500;
    int ERROR_HOME_ASSISTANT_FAILED = 0x02502;

    // Broadcast Event Intent Filters
    String BROADCAST_NOTIF = "com.avariohome.avario.PUSH_NOTIFICATION";
    String BROADCAST_MEDIA = "com.avariohome.avario.MEDIA";
    String BROADCAST_STATE_CHANGED = "com.avariohome.avario.STATE_CHANGE";
    String BROADCAST_ROOM_CHANGED = "com.avariohome.avario.ROOM_CHANGED";
    String BROADCAST_BOOTSTRAP_CHANGED = "com.avariohome.avario.BOOTSTRAP_CHANGED";
    String LOGTAG_EMERGENCY = "Avario/Emergency";
}
